---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  PyPI:
    name: Build and publish Python distributions to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pdm-project/setup-pdm@main
        name: Setup Python and PDM
        with:
          python-version: 3.9
      - name: Build package
        run: make build-package
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
